export const ACTIONS = {
  START: 'USERS_WORKER_FOR_COMPANIES/START',
  ERROR: 'USERS_WORKER_FOR_COMPANIES/ERROR',

  SET_COMPANY_USERS: 'USERS_WORKER_FOR_COMPANIES/SET_COMPANY_USERS',
  DELETE_COMPANY_USERS: 'USERS_WORKER_FOR_COMPANIES/DELETE_COMPANY_USERS',
};
